apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dw_test1
  description: Use this api
  tags:
    - rest
    - openapi
  links:
    - url: "https://github.com/davewins/apis"
      title: GitHub Repo 
      icon: github 
    - url: "https://github.com/davewins/apis/blob/master/dw_test1.json"
      title: API Spec 
      icon: code
spec:
  type: openapi
  owner: finance-department
  lifecycle: experimental
  definition:
    "$text": "./dw_test1.json"
