apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: null
  description: null
  tags:
    - rest
    - openapi
  links:
    - url: https://github.com/mmussett/flogo-hello-world
      title: GitHub Repo 
      icon: github 
    - url: https://github.com/mmussett/flogo-hello-world/blob/main/api-spec/openapi.yaml
      title: API Spec 
      icon: code
spec:
  type: openapi
  owner: finance-team
  lifecycle: experimental
