apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: NewLoan9
  description: New description goes here and now add a new part
  tags:
    - rest
    - openapi
  links:
    - url: "https://github.com/davewins/apis"
      title: GitHub Repo 
      icon: github 
    - url: "https://github.com/davewins/apis/blob/master/NewLoan9_1719393353639.json"
      title: API Spec 
      icon: code
spec:
  type: openapi
  owner: finance-department
  lifecycle: experimental
  definition:
     "$text": "./NewLoan9_1719393353639.json"
