apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  links:
#    - title: VSCode Editor (File)
#      url: vscode://file/${{ values.localFolder }}/call-service.flogo
#    - title: VSCode Editor (Folder)
#      url: vscode://file/${{ values.localFolder }}
    - title: Open in VSCode
      icon: dashboard
      url: 'vscode://vscode.git/clone?url=https://github.com/davewins/apis/'
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: development
  owner: ${{values.owner | dump}}
  providesApis: ['${{values.name}}-api']
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ${{values.name}}-api-location
spec:
  targets:
    - ./../../${{values.api}}.yaml
